export enum ErrorCode {
  // Authorization errors
  UNAUTHORIZED_METHOD_CALL = 'UNAUTHORIZED_METHOD_CALL',
  
  // Model instantiation errors
  DIRECT_INSTANTIATION_NOT_ALLOWED = 'DIRECT_INSTANTIATION_NOT_ALLOWED',
  
  // Field access errors
  FIELD_NOT_READABLE = 'FIELD_NOT_READABLE',
  FIELD_NOT_INITIALIZED = 'FIELD_NOT_INITIALIZED',
  FIELD_TYPE_MISMATCH = 'FIELD_TYPE_MISMATCH',
  FIELD_NOT_WRITABLE = 'FIELD_NOT_WRITABLE',
  FIELD_IS_COMPUTED = 'FIELD_IS_COMPUTED',
  FIELD_SET_ERROR = 'FIELD_SET_ERROR',
  FIELD_UNSET_ERROR = 'FIELD_UNSET_ERROR',
  FIELD_NO_GENERATOR = 'FIELD_NO_GENERATOR',
  FIELD_ALREADY_GENERATED = 'FIELD_ALREADY_GENERATED',
  FIELD_CANNOT_GENERATE_EXISTING = 'FIELD_CANNOT_GENERATE_EXISTING',
  FIELD_NO_COMPUTE = 'FIELD_NO_COMPUTE',
  FIELD_COMPUTE_NOT_MUTABLE = 'FIELD_COMPUTE_NOT_MUTABLE',
  
  // Field validator errors
  FIELD_NOT_NULLABLE = 'FIELD_NOT_NULLABLE',
  FIELD_VALIDATOR_FAILED = 'FIELD_VALIDATOR_FAILED',
  FIELD_VALIDATORS_FAILED = 'FIELD_VALIDATORS_FAILED',

  // Association errors
  ASSOCIATION_INCOMPLETE = 'ASSOCIATION_INCOMPLETE',
  ASSOCIATION_INVALID = 'ASSOCIATION_INVALID',
  ASSOCIATION_VALIDATOR_NOT_FOUND = 'ASSOCIATION_VALIDATOR_NOT_FOUND',
  
  // Model errors
  ID_FIELD_CANNOT_BE_EXCLUDED = 'ID_FIELD_CANNOT_BE_EXCLUDED',
  MODEL_FIELD_VALIDATION_FAILED = 'MODEL_FIELD_VALIDATION_FAILED',
  
  // Context errors
  ASYNC_LOCAL_STORAGE_REQUIRES_NODEJS = 'ASYNC_LOCAL_STORAGE_REQUIRES_NODEJS',
  CONTEXT_USE_RUN_METHOD = 'CONTEXT_USE_RUN_METHOD',
  CONTEXT_AUTO_RESET = 'CONTEXT_AUTO_RESET',
  ASYNC_LOCAL_STORAGE_SETUP_FAILED = 'ASYNC_LOCAL_STORAGE_SETUP_FAILED',
  CONTEXT_ADAPTER_REQUIRED = 'CONTEXT_ADAPTER_REQUIRED',
};
